export const TOOL_REGISTRY = {
  merge: {
    id: 'merge',
    label: 'Merge',
    title: 'Merge PDFs',
    icon: 'Merge',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: true,
    importLabel: 'Import PDFs',
  },
  split: {
    id: 'split',
    label: 'Split',
    title: 'Split PDF',
    icon: 'Split',
    view: 'page-grid',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  compress: {
    id: 'compress',
    label: 'Compress',
    title: 'Compress PDF',
    icon: 'Compress',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  organize: {
    id: 'organize',
    label: 'Organize',
    title: 'Organize Pages',
    icon: 'Organize',
    view: 'page-grid',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  addtext: {
    id: 'addtext',
    label: 'Add Text',
    title: 'Add Text / Sign',
    icon: 'Annotate',
    view: 'page-canvas',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  pagenums: {
    id: 'pagenums',
    label: 'Page Numbers',
    title: 'Page Numbers',
    icon: 'Numbers',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  watermark: {
    id: 'watermark',
    label: 'Watermark',
    title: 'Add Watermark',
    icon: 'Watermark',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  encrypt: {
    id: 'encrypt',
    label: 'Encrypt',
    title: 'Encrypt PDF',
    icon: 'Encrypt',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  extract: {
    id: 'extract',
    label: 'Extract Text',
    title: 'Extract Text',
    icon: 'Extract',
    view: 'composer',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  pdf2jpg: {
    id: 'pdf2jpg',
    label: 'PDF to JPG',
    title: 'PDF to JPG',
    icon: 'Export',
    view: 'summary',
    accept: '.pdf,application/pdf',
    multiple: false,
    importLabel: 'Import PDF',
  },
  img2pdf: {
    id: 'img2pdf',
    label: 'Images to PDF',
    title: 'Images to PDF',
    icon: 'Images',
    view: 'composer',
    accept: 'image/jpeg,image/png,image/webp',
    multiple: true,
    importLabel: 'Import Images',
  },
  html2pdf: {
    id: 'html2pdf',
    label: 'HTML to PDF',
    title: 'HTML to PDF',
    icon: 'HTML',
    view: 'composer',
    accept: '.html,.htm,text/html',
    multiple: false,
    importLabel: 'Import HTML',
  },
};

export const TOOL_ORDER = [
  'merge',
  'split',
  'compress',
  'organize',
  'addtext',
  'pagenums',
  'watermark',
  'encrypt',
  'extract',
  'pdf2jpg',
  'img2pdf',
  'html2pdf',
];

export const DEFAULT_TOOL = 'merge';

export function getToolDefinition(tool) {
  return TOOL_REGISTRY[tool];
}
